option(TORQUE_XR "Enable the mixed reality module" ON)
option(TORQUE_XR_OPENVR "Use OpenVR SDK for XR rendering" ON)

if(TORQUE_XR)
  message("Enabling Mixed Reality Module")
  set(TORQUE_COMPILE_DEFINITIONS ${TORQUE_COMPILE_DEFINITIONS} TORQUE_XR)
  if (TORQUE_XR_OPENVR)
    message("Mixed Reality Module: Enabling OpenVR Backend")
    if(TORQUE_XR_OPENVR_SDK_PATH STREQUAL "")
      set(TORQUE_XR_OPENVR_SDK_PATH "" CACHE PATH "Path to the OpenVR SDK.")
    endif()
    torqueAddSourceDirectories("${CMAKE_SOURCE_DIR}/Engine/source/platform/input/openVR")
    find_package(OpenVR REQUIRED)
    set(TORQUE_LINK_LIBRARIES ${TORQUE_LINK_LIBRARIES} OpenVR::OpenVR)

    file(GLOB_RECURSE TORQUE_XR_OPENVR_SOURCES "${CMAKE_SOURCE_DIR}/Engine/source/platform/input/openVR/*.cpp" "${CMAKE_SOURCE_DIR}/Engine/source/platform/input/openVR/*.h" )
    set(TORQUE_SOURCE_FILES ${TORQUE_SOURCE_FILES} ${TORQUE_XR_OPENVR_SOURCES})
    source_group(TREE "${CMAKE_SOURCE_DIR}/Engine/source/platform/input/openVR" PREFIX "Modules/XR/OpenVR" FILES ${TORQUE_XR_OPENVR_SOURCES})
  endif()
endif()